### ISSUE TITLE
vue.defineComponent is not a function

### ISSUE THREAD

**Issue by Rasool-deldar** [posva/vue-use-spring#145]
Hi, I wanted to use the [vue-use-gesture](https://vue-use-gesture.netlify.app/docs/) package which supports vue 2 but your package gives an error please follow up to fix this problem.

Click on the [example](https://codesandbox.io/s/zen-goldwasser-3uvhy?file=/pages/index.vue)

![image](https://user-images.githubusercontent.com/58503211/114900160-d9822e80-9e28-11eb-995c-f0bcfd329c48.png)

![image](https://user-images.githubusercontent.com/58503211/114900184-e010a600-9e28-11eb-8be9-3ea91c72ae36.png)

**Comment by jeffrey-dot-li** [comment]
Same issue, using Vue 3 with nuxt. I'm assuming it has something to do with Nuxt not using vue's built in implementation of defineComponent but instead defines its own in '@nuxtjs/composition-api'.

**Comment by posva** [comment]
I'm not the author of that example 😓
It's likely misconfigured, please see with the author
